/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppBinsRouteImport } from './routes/app.bins'
import { Route as AppCitizenRouteImport } from './routes/app.citizen'
import { Route as AppDispatchRouteImport } from './routes/app.dispatch'
import { Route as AppFieldRouteImport } from './routes/app.field'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppPredictionsRouteImport } from './routes/app.predictions'
import { Route as AppIncidentsIndexRouteImport } from './routes/app.incidents.index'
import { Route as AppIncidentsIdRouteImport } from './routes/app.incidents.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBinsRoute = AppBinsRouteImport.update({
  id: '/bins',
  path: '/bins',
  getParentRoute: () => AppRoute,
} as any)
const AppCitizenRoute = AppCitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => AppRoute,
} as any)
const AppDispatchRoute = AppDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AppRoute,
} as any)
const AppFieldRoute = AppFieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictionsRoute = AppPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsIndexRoute = AppIncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsIdRoute = AppIncidentsIdRouteImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/bins': typeof AppBinsRoute
  '/app/citizen': typeof AppCitizenRoute
  '/app/dispatch': typeof AppDispatchRoute
  '/app/field': typeof AppFieldRoute
  '/app/map': typeof AppMapRoute
  '/app/predictions': typeof AppPredictionsRoute
  '/app/': typeof AppIndexRoute
  '/app/incidents/$id': typeof AppIncidentsIdRoute
  '/app/incidents/': typeof AppIncidentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/bins': typeof AppBinsRoute
  '/app/citizen': typeof AppCitizenRoute
  '/app/dispatch': typeof AppDispatchRoute
  '/app/field': typeof AppFieldRoute
  '/app/map': typeof AppMapRoute
  '/app/predictions': typeof AppPredictionsRoute
  '/app': typeof AppIndexRoute
  '/app/incidents/$id': typeof AppIncidentsIdRoute
  '/app/incidents': typeof AppIncidentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/bins': typeof AppBinsRoute
  '/app/citizen': typeof AppCitizenRoute
  '/app/dispatch': typeof AppDispatchRoute
  '/app/field': typeof AppFieldRoute
  '/app/map': typeof AppMapRoute
  '/app/predictions': typeof AppPredictionsRoute
  '/app/': typeof AppIndexRoute
  '/app/incidents/$id': typeof AppIncidentsIdRoute
  '/app/incidents/': typeof AppIncidentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/bins'
    | '/app/citizen'
    | '/app/dispatch'
    | '/app/field'
    | '/app/map'
    | '/app/predictions'
    | '/app/'
    | '/app/incidents/$id'
    | '/app/incidents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/bins'
    | '/app/citizen'
    | '/app/dispatch'
    | '/app/field'
    | '/app/map'
    | '/app/predictions'
    | '/app'
    | '/app/incidents/$id'
    | '/app/incidents'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/bins'
    | '/app/citizen'
    | '/app/dispatch'
    | '/app/field'
    | '/app/map'
    | '/app/predictions'
    | '/app/'
    | '/app/incidents/$id'
    | '/app/incidents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bins': {
      id: '/app/bins'
      path: '/bins'
      fullPath: '/app/bins'
      preLoaderRoute: typeof AppBinsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/citizen': {
      id: '/app/citizen'
      path: '/citizen'
      fullPath: '/app/citizen'
      preLoaderRoute: typeof AppCitizenRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dispatch': {
      id: '/app/dispatch'
      path: '/dispatch'
      fullPath: '/app/dispatch'
      preLoaderRoute: typeof AppDispatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/field': {
      id: '/app/field'
      path: '/field'
      fullPath: '/app/field'
      preLoaderRoute: typeof AppFieldRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/predictions': {
      id: '/app/predictions'
      path: '/predictions'
      fullPath: '/app/predictions'
      preLoaderRoute: typeof AppPredictionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/incidents/': {
      id: '/app/incidents/'
      path: '/incidents'
      fullPath: '/app/incidents/'
      preLoaderRoute: typeof AppIncidentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/incidents/$id': {
      id: '/app/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/app/incidents/$id'
      preLoaderRoute: typeof AppIncidentsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBinsRoute: typeof AppBinsRoute
  AppCitizenRoute: typeof AppCitizenRoute
  AppDispatchRoute: typeof AppDispatchRoute
  AppFieldRoute: typeof AppFieldRoute
  AppMapRoute: typeof AppMapRoute
  AppPredictionsRoute: typeof AppPredictionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppIncidentsIdRoute: typeof AppIncidentsIdRoute
  AppIncidentsIndexRoute: typeof AppIncidentsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBinsRoute: AppBinsRoute,
  AppCitizenRoute: AppCitizenRoute,
  AppDispatchRoute: AppDispatchRoute,
  AppFieldRoute: AppFieldRoute,
  AppMapRoute: AppMapRoute,
  AppPredictionsRoute: AppPredictionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppIncidentsIdRoute: AppIncidentsIdRoute,
  AppIncidentsIndexRoute: AppIncidentsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
